<?php
/**
 * ClassyLlama_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @copyright  Copyright (c) 2016 Avalara, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?= $secureRenderer->renderTag('script', ['type' => 'text/x-magento-init'], '
    {
        "*": {
            "addressValidationModal": {
                "validationEnabled": ' . (int)$this->isValidationEnabled() . ',
                "hasChoice": "' . $this->getChoice() . '",
                "instructions": "' . $this->getInstructions() . '",
                "errorInstructions": "' . $this->getErrorInstructions() . '",
                "countriesEnabled": "' . $this->getCountriesEnabled() . '"
            }
        }
    }
', false); ?>

<?= $secureRenderer->renderTag('script', ['type' => 'text/javascript'], "
    require([
        'mage/url'
    ], function(url) {
        // Set baseUrl so that the urlBuilder JS module has access to it
        // Calling getUrl instead of getBaseUrl as the latter has been overridden in
        // \ClassyLlama\AvaTax\Block\CustomerAddress to return a different url
        return url.setBaseUrl('" . $block->getUrl() . "');
    });
", false); ?>

<?= $secureRenderer->renderTag('script', ['type' => 'text/javascript'], "\nwindow.avaTaxStoreCode = " . $this->getStoreCode() . ";\n", false); ?>
